<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18982" started-at="2019-05-02T07:25:46Z" finished-at="2019-05-02T07:26:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18982" started-at="2019-05-02T07:25:46Z" finished-at="2019-05-02T07:26:05Z">
      <class name="testmu.TestPage12">
        <test-method status="PASS" signature="starteReport()[pri:0, instance:testmu.TestPage12@1fbc7afb]" name="starteReport" is-config="true" duration-ms="119" started-at="2019-05-02T12:55:46Z" finished-at="2019-05-02T12:55:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- starteReport -->
        <test-method status="PASS" signature="checkAlllinks()[pri:0, instance:testmu.TestPage12@1fbc7afb]" name="checkAlllinks" duration-ms="18562" started-at="2019-05-02T12:55:46Z" finished-at="2019-05-02T12:56:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkAlllinks -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testmu.TestPage12@1fbc7afb]" name="getResult" is-config="true" duration-ms="3" started-at="2019-05-02T12:56:04Z" finished-at="2019-05-02T12:56:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=checkAlllinks status=SUCCESS method=TestPage12.checkAlllinks()[pri:0, instance:testmu.TestPage12@1fbc7afb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="testToFail()[pri:0, instance:testmu.TestPage12@1fbc7afb]" name="testToFail" duration-ms="3" started-at="2019-05-02T12:56:05Z" finished-at="2019-05-02T12:56:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testmu.TestPage12.testToFail(TestPage12.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testToFail -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testmu.TestPage12@1fbc7afb]" name="getResult" is-config="true" duration-ms="0" started-at="2019-05-02T12:56:05Z" finished-at="2019-05-02T12:56:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testToFail status=FAILURE method=TestPage12.testToFail()[pri:0, instance:testmu.TestPage12@1fbc7afb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:testmu.TestPage12@1fbc7afb]" name="endReport" is-config="true" duration-ms="279" started-at="2019-05-02T12:56:05Z" finished-at="2019-05-02T12:56:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- testmu.TestPage12 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
